name: Accuknox SAST

on:
  workflow_dispatch:

jobs:
   secret-scan:
     runs-on: ubuntu-latest

     steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Secret Scan
        uses: accuknox/secret-scan-action@latest
        with:
          branch: "main"
          results: ""
          exclude_paths: "tests/,docs/"
          additional_arguments: ""
          base_command: ""
          upload_results: true
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          soft_fail: true

   accuknox-cicd:
    needs: secret-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Run Accuknox SAST: Opengrep"
        uses: accuknox/sast-scan-opengrep-action@latest
        with:
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          soft_fail: "true"
          severity: "HIGH"
